# Generated by Django 5.1.7 on 2025-03-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_collector', models.CharField(editable=False, max_length=20, unique=True)),
                ('collectorUsername', models.CharField(max_length=20, unique=True)),
                ('collectorName', models.TextField(blank=True, max_length=15, null=True)),
                ('collectorFirstSurname', models.TextField(blank=True, max_length=15, null=True)),
                ('collectorSecondSurname', models.TextField(blank=True, max_length=15, null=True)),
                ('collectorPhoneNumber', models.CharField(blank=True, max_length=16, null=True)),
                ('collectorGmail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='fsurname',
            new_name='sellerFirstSurname',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='gmail',
            new_name='sellerGmail',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='name',
            new_name='sellerName',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='phone_number',
            new_name='sellerPhoneNumber',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='ssurname',
            new_name='sellerSecondSurname',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='username',
            new_name='sellerUsername',
        ),
    ]
