# Generated by Django 5.1.7 on 2025-07-04 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_vehicle"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorprofile",
            name="vehicule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_seller",
                to="collection.vehicle",
            ),
        ),
    ]
