# Generated by Django 5.1.7 on 2025-03-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_collector_rename_fsurname_seller_sellerfirstsurname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='ID_collector',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='collectorFirstSurname',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='collectorGmail',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='collectorName',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='collectorPhoneNumber',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='collectorSecondSurname',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='ID_seller',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='sellerFirstSurname',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='sellerGmail',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='sellerName',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='sellerPhoneNumber',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='sellerSecondSurname',
        ),
        migrations.AddField(
            model_name='collector',
            name='collectorEmail',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='collectorPhone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='collectorpassword',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='sellerEmail',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='sellerPhone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='sellerpassword',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='collector',
            name='collectorUsername',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='sellerUsername',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='collector',
            name='id_collector',
            field=models.CharField(blank=True, editable=False, max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='id_seller',
            field=models.CharField(blank=True, editable=False, max_length=11, primary_key=True, serialize=False),
        ),
    ]
