# Generated by Django 5.1.7 on 2025-07-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_collectorprofile_vehicule"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectorprofile",
            old_name="vehicule",
            new_name="vehicle",
        ),
    ]
