# Generated by Django 5.1.7 on 2025-07-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_vehicule_collectorprofile_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorprofile",
            name="has_active_route",
            field=models.BooleanField(default=False),
        ),
    ]
