# Generated by Django 5.1.7 on 2025-06-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_collector_id_collector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='collectorUsername',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='sellerUsername',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
