# Generated by Django 5.1.7 on 2025-03-09 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_collector_rename_fsurname_seller_sellerfirstsurname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_order', models.CharField(editable=False, max_length=14, unique=True)),
                ('orderCreationDay', models.DateTimeField(auto_now_add=True)),
                ('routeStartLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('routeEndLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('routeDistance', models.FloatField(blank=True, null=True)),
                ('routeEstimatedTime', models.DurationField(blank=True, null=True)),
                ('assigned_collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.collector')),
            ],
        ),
    ]
