# Generated by Django 5.1.7 on 2025-06-20 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("es_personalizado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_order",
                    models.CharField(editable=False, max_length=14, unique=True),
                ),
                ("orderCreationDay", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "comision",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tip",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True,
                        choices=[("efectivo", "Efectivo"), ("tarjeta", "Tarjeta")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "id_collector",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "collector"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_as_collector",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_seller",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "seller"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="collection.order",
                    ),
                ),
            ],
        ),
    ]
