# Generated by Django 5.1.7 on 2025-07-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="metodo_pago",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("card", "Card")],
                max_length=20,
                null=True,
            ),
        ),
    ]
