# Generated by Django 5.1.7 on 2025-07-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_alter_orderitem_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("auto", "Auto"),
                            ("camion", "Camión"),
                            ("pickup", "Camioneta Pick Up"),
                            ("carreta", "Carreta"),
                            ("caminar", "Caminar"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "capacidad",
                    models.PositiveIntegerField(
                        blank=True, help_text="Capacidad máxima en kg ", null=True
                    ),
                ),
                (
                    "velocidad",
                    models.PositiveIntegerField(
                        blank=True, help_text="Velocidad promedio en km/h", null=True
                    ),
                ),
                (
                    "consumo",
                    models.PositiveIntegerField(
                        blank=True, help_text="Consumo aproximado en L/km", null=True
                    ),
                ),
            ],
        ),
    ]
