# Generated by Django 5.1.7 on 2025-06-01 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_order_assigned_collector'),
        ('users', '0004_alter_collector_collectorusername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_personalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ID_order',
            new_name='id_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='routeDistance',
        ),
        migrations.RemoveField(
            model_name='order',
            name='routeEndLocation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='routeEstimatedTime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='routeStartLocation',
        ),
        migrations.AddField(
            model_name='order',
            name='id_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.collector'),
        ),
        migrations.AddField(
            model_name='order',
            name='id_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collection.order')),
            ],
        ),
    ]
