# Generated by Django 5.1.7 on 2025-07-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_alter_order_metodo_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
