# Generated by Django 5.1.7 on 2025-06-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], max_length=20, null=True),
        ),
    ]
