# Generated by Django 5.1.7 on 2025-06-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0005_order_direccion_order_latitud_order_longitud_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="latitud",
            new_name="lat",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="longitud",
            new_name="lot",
        ),
        migrations.RemoveField(
            model_name="order",
            name="direccion",
        ),
        migrations.AddField(
            model_name="order",
            name="comision",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="tip",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="metodo_pago",
            field=models.CharField(
                blank=True,
                choices=[("efectivo", "Efectivo"), ("tarjeta", "Tarjeta")],
                max_length=20,
                null=True,
            ),
        ),
    ]
