# Generated by Django 5.1.7 on 2025-06-20 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "collection",
            "0006_rename_latitud_order_lat_rename_longitud_order_lot_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="lot",
            new_name="lon",
        ),
    ]
