# Generated by Django 5.1.7 on 2025-03-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_route', models.CharField(editable=False, max_length=11, unique=True)),
                ('routeCreationDay', models.DateTimeField(auto_now_add=True)),
                ('routeGeometry', models.CharField(editable=False, max_length=500)),
            ],
        ),
    ]
