# Generated by Django 5.1.7 on 2025-03-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='id',
        ),
        migrations.AlterField(
            model_name='route',
            name='ID_route',
            field=models.CharField(editable=False, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
