# Generated by Django 5.1.7 on 2025-06-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_remove_route_id_alter_route_id_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='routeCreationDay',
        ),
        migrations.AddField(
            model_name='route',
            name='routeDistance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='routeEndLocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='routeEstimatedTime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='routeStartLocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
