# Generated by Django 5.1.7 on 2025-07-06 23:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0007_alter_order_status"),
        ("routes", "0003_remove_route_routecreationday_route_routedistance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="routeEndLocation",
            new_name="endlat",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="routeStartLocation",
            new_name="endlon",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="ID_route",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="route",
            name="routeEstimatedTime",
        ),
        migrations.AddField(
            model_name="route",
            name="lat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="lon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="order",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": "collector"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route",
                to="collection.order",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="routeCreationDay",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="route",
            name="routeGeometry",
            field=models.TextField(),
        ),
    ]
