# Generated by Django 5.1.7 on 2025-07-06 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0007_alter_order_status"),
        ("routes", "0004_rename_routeendlocation_route_endlat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route",
                to="collection.order",
            ),
        ),
    ]
