# Generated by Django 5.1.7 on 2025-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0005_alter_route_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="routeGeometry",
            field=models.TextField(blank=True, null=True),
        ),
    ]
